version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: helix_postgres
    environment:
      POSTGRES_USER: helix_user
      POSTGRES_PASSWORD: helix_password
      POSTGRES_DB: helix_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
